{{- if (include "discourse.redisCreateSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "discourse.fullname" . }}-redis
  labels: {{- include "discourse.labels" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "discourse.tplValue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "discourse.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) (not (empty .Values.externalRedis.password)) }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
{{- end }}
